# Generated by Django 5.1.7 on 2025-11-19 05:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberattack', '0002_systemmaintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firewall_enabled', models.BooleanField(default=True)),
                ('auto_block_enabled', models.BooleanField(default=True)),
                ('block_duration', models.IntegerField(default=3600)),
                ('max_attempts', models.IntegerField(default=5)),
                ('whitelist_ips', models.TextField(blank=True, help_text='Comma-separated IP addresses')),
                ('block_threshold', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firewall Configuration',
                'verbose_name_plural': 'Firewall Configurations',
            },
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('block_ip', 'Block IP Address'), ('block_attack', 'Block Attack Type'), ('rate_limit', 'Rate Limiting'), ('geo_block', 'Geographic Block')], max_length=20)),
                ('rule_value', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.IntegerField(choices=[(0, 'BENIGN'), (1, 'DDoS'), (2, 'FTP-Patator'), (3, 'SSH-Patator'), (4, 'DoS Hulk'), (5, 'DoS GoldenEye'), (6, 'DoS Slowloris'), (7, 'DoS Slowhttptest'), (8, 'Heartbleed'), (9, 'Web Attack – Brute Force'), (10, 'Web Attack – XSS'), (11, 'Web Attack – SQL Injection'), (12, 'Infiltration')])),
                ('attack_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('source_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('os_info', models.CharField(blank=True, max_length=200)),
                ('browser_info', models.CharField(blank=True, max_length=200)),
                ('device_type', models.CharField(blank=True, max_length=100)),
                ('screen_resolution', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('isp', models.CharField(blank=True, max_length=200)),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('block_duration', models.IntegerField(default=3600)),
                ('destination_port', models.FloatField()),
                ('flow_bytes_s', models.FloatField()),
                ('flow_packets_s', models.FloatField()),
                ('firewall_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyberattack.firewallrule')),
            ],
            options={
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['source_ip'], name='cyberattack_source__6c64d9_idx'), models.Index(fields=['blocked_at'], name='cyberattack_blocked_1d22ba_idx'), models.Index(fields=['attack_type'], name='cyberattack_attack__c65097_idx')],
            },
        ),
    ]
