# Generated by Django 5.1.7 on 2025-11-19 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cyberattack', '0003_firewallconfig_firewallrule_blockedattack'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityalert',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='description',
            field=models.TextField(default='Security alert'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='metadata',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
