# Generated by Django 5.1.7 on 2025-11-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberattack', '0005_add_resolved_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='securityalert',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='securityalert',
            name='acknowledged_by',
        ),
        migrations.RemoveField(
            model_name='securityalert',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='securityalert',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='securityalert',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='securityalert',
            name='status',
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='alert_type',
            field=models.CharField(default='Security Alert', max_length=50),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='attack_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cyberattack.attacklog'),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='description',
            field=models.TextField(),
        ),
    ]
